version: '3.1'

services:
  postgres:
    build:
      context: docker/postgres
      dockerfile: Dockerfile
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./docker/postgres/.data:/var/lib/postgresql/data

  web:
    image: ghcr.io/tontan2545/nql-web:latest
    ports:
      - 3000:3000
    env_file:
      - apps/web/.env.local
    depends_on:
      - postgres
      - server

  server:
    image: ghcr.io/tontan2545/nql-server:latest
    restart: always
    ports:
      - 8000:8000
    env_file:
      - apps/server/.env
    depends_on:
      - postgres
    
    