version: '3.1'

services:
  pagila:
    image: postgres:9.6
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pagila
  redis:
    image: redis/redis-stack
    ports:
      - 6379:6379
      - 8001:8001
    environment:
      - REDIS_ARGS="--requirepass redis"