version: '3.1'

services:
  postgres:
    build:
      context: docker/postgres
      dockerfile: Dockerfile
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./docker/postgres/.data:/var/lib/postgresql/data