name: publish

on:
  push:
    branches: ["main"]

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  FRONTEND_IMAGE_NAME: ${{ github.actor }}/nql-web:latest
  BACKEND_IMAGE_NAME: ${{ github.actor }}/nql-server:latest

jobs:
  publish:
    name: Publish Images
    runs-on: ubuntu-latest
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}
      - name: Build and Publish Web
        run: |
          docker build -f apps/web/Dockerfile . --tag ${{ env.REGISTRY }}/${{ env.FRONTEND_IMAGE_NAME }}
          docker push ${{ env.REGISTRY }}/${{ env.FRONTEND_IMAGE_NAME }}
      - name: Build and Publish Server
        run: |
          docker build -f apps/web/Dockerfile . --tag ${{ env.REGISTRY }}/${{ env.BACKEND_IMAGE_NAME }}
          docker push ${{ env.REGISTRY }}/${{ env.BACKEND_IMAGE_NAME }}
