name: publish

on:
  push:
    branches: ["main"]

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  FRONTEND_IMAGE_NAME: ${{ github.actor }}/nql-web:latest
  BACKEND_IMAGE_NAME: ${{ github.actor }}/nql-server:latest

jobs:
  publish:
    name: publish image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Login
        run: |
          echo ${{ secrets.AT }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Build and Publish
        run: |
          docker build -f apps/web/Dockerfile . --tag ${{ env.REGISTRY }}/${{ env.FRONTEND_IMAGE_NAME }}
          docker push ${{ env.REGISTRY }}/${{ env.FRONTEND_IMAGE_NAME }}
